version: "3"

services:
    web: 
      container_name: exampleapp
      image: christianphp/mi-node-app:1.0.0
      restart: always
      #build: .
      ports:
          - "4000:3000"
      links:
          - mongo
      volumes:
          - .:/usr/src/app
    mongo:
        container_name: mymongodatabase
        image: mongo:4.4.11
        ports: 
            - "27018:27017"
        #environment:
            #- MONGO_INITDB_ROOT_USERNAME=admin
            #- MONGO_INITDB_ROOT_PASSWORD=password
        logging:
            driver: none
        volumes:
          - mongo-data:/data/db
    mongo-express:
        image: mongo-express
        restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
        ports:
          - 8080:8081
        #environment:
        #- ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        #- ME_CONFIG_MONGODB_ADMINPASSWORD=password
        #- ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local